// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace proba1.Migrations
{
    [DbContext(typeof(AplikacijaContext))]
    partial class FakultetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Aplikacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Aplikacija");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AplikacijaID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KorisnickoIme");

                    b.Property<string>("Lozinka")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lozinka");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prezime");

                    b.Property<string>("SALT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AplikacijaID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Models.Pozoriste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AplikacijaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AplikacijaID");

                    b.ToTable("Pozoriste");
                });

            modelBuilder.Entity("Models.Predstava", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AplikacijaID")
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reditelj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zanr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AplikacijaID");

                    b.ToTable("Predstava");
                });

            modelBuilder.Entity("Models.Rezervacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AplikacijaID")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int?>("PredstavaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AplikacijaID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("PredstavaID");

                    b.ToTable("Rezervacija");
                });

            modelBuilder.Entity("Models.Sediste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<int?>("PredstavaID")
                        .HasColumnType("int");

                    b.Property<int>("Red")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaID")
                        .HasColumnType("int");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Zauzeto")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("PredstavaID");

                    b.HasIndex("RezervacijaID");

                    b.ToTable("Sediste");
                });

            modelBuilder.Entity("Models.Slika", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PredstavaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PredstavaID");

                    b.ToTable("Slika");
                });

            modelBuilder.Entity("Models.Umetnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AplikacijaID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prezime");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AplikacijaID");

                    b.ToTable("Umetnik");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.HasOne("Models.Aplikacija", "Aplikacija")
                        .WithMany("korisnik")
                        .HasForeignKey("AplikacijaID");

                    b.Navigation("Aplikacija");
                });

            modelBuilder.Entity("Models.Pozoriste", b =>
                {
                    b.HasOne("Models.Aplikacija", "Aplikacija")
                        .WithMany("Pozoriste")
                        .HasForeignKey("AplikacijaID");

                    b.Navigation("Aplikacija");
                });

            modelBuilder.Entity("Models.Predstava", b =>
                {
                    b.HasOne("Models.Aplikacija", "Aplikacija")
                        .WithMany("Predstava")
                        .HasForeignKey("AplikacijaID");

                    b.Navigation("Aplikacija");
                });

            modelBuilder.Entity("Models.Rezervacija", b =>
                {
                    b.HasOne("Models.Aplikacija", null)
                        .WithMany("Rezervacija")
                        .HasForeignKey("AplikacijaID");

                    b.HasOne("Models.Korisnik", "Korisnik")
                        .WithMany("Rezervacija")
                        .HasForeignKey("KorisnikID");

                    b.HasOne("Models.Predstava", "Predstava")
                        .WithMany("Rezervacija")
                        .HasForeignKey("PredstavaID");

                    b.Navigation("Korisnik");

                    b.Navigation("Predstava");
                });

            modelBuilder.Entity("Models.Sediste", b =>
                {
                    b.HasOne("Models.Predstava", "Predstava")
                        .WithMany("Sediste")
                        .HasForeignKey("PredstavaID");

                    b.HasOne("Models.Rezervacija", "Rezervacija")
                        .WithMany("Sediste")
                        .HasForeignKey("RezervacijaID");

                    b.Navigation("Predstava");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("Models.Slika", b =>
                {
                    b.HasOne("Models.Predstava", "Predstava")
                        .WithMany("Slike")
                        .HasForeignKey("PredstavaID");

                    b.Navigation("Predstava");
                });

            modelBuilder.Entity("Models.Umetnik", b =>
                {
                    b.HasOne("Models.Aplikacija", "Aplikacija")
                        .WithMany("Umetnik")
                        .HasForeignKey("AplikacijaID");

                    b.Navigation("Aplikacija");
                });

            modelBuilder.Entity("Models.Aplikacija", b =>
                {
                    b.Navigation("korisnik");

                    b.Navigation("Pozoriste");

                    b.Navigation("Predstava");

                    b.Navigation("Rezervacija");

                    b.Navigation("Umetnik");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("Models.Predstava", b =>
                {
                    b.Navigation("Rezervacija");

                    b.Navigation("Sediste");

                    b.Navigation("Slike");
                });

            modelBuilder.Entity("Models.Rezervacija", b =>
                {
                    b.Navigation("Sediste");
                });
#pragma warning restore 612, 618
        }
    }
}
